[workspace]
members = [
  "crates/hive-cli",
  "crates/hive-core",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
repository = "https://github.com/gvm1229/aigent-hive"
license = "GPL-3.0-only"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"
