[package]
name = "hive-core"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
ed25519-dalek.workspace = true
jsonschema.workspace = true
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_json_canonicalizer.workspace = true
serde_yaml.workspace = true
sha2.workspace = true

[lints]
workspace = true
